[package]
name = "flange_token"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.17.0"
spl-token = { version="3.5.0", features = [ "no-entrypoint" ] }      
borsh = "0.10.3" 
ahash = "=0.8.6"
metaplex = "0.0.1"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]