[package]
name = "flange_token"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.17.0"
spl-token = { version="3.5.0", features = [ "no-entrypoint" ] }      
borsh = "0.10.3" 
ahash = "=0.8.6"

[lib]
crate-type = ["cdylib", "lib"]
