[package]
name = "flange_token"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.1.0"  # compatible with Solana CLI 1.16+
spl-token = "3.5.0"       # latest compatible version with solana-program 2.x
borsh = "0.9.1"           # you can keep borsh at the same version