[package]
name = "flange_token"
version = "0.2.0"
authors = ["Milton Black"]
edition = "2021"

[dependencies]
solana-program = "=2.1.0"
solana-pubkey = { version = "=2.1.0", features = ["solana-sha256-hasher"] }
spl-token = { version="7.0.0", features = [ "no-entrypoint" ] }      
metaplex = "0.0.1"

# Override solana-pubkey dependency
[patch.crates-io]
solana-pubkey = { git = "https://github.com/solana-labs/solana", branch = "master" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]